
# Ground
[[world]]
Sphere.center = [0, -100.5, -1]
Sphere.radius = 100
Sphere.material.Lambertian.albedo = [0.8, 0.8, 0.0]

# Center
[[world]]
Sphere.center = [0, 0, -1.0]
Sphere.radius = 0.5
Sphere.material.Lambertian.albedo = [0.1, 0.2, 0.5]

# Left
[[world]]
Sphere.center = [-1, 0, -1]
Sphere.radius = -0.45
Sphere.material.Dielectric.refractive_index = 1.5
[[world]]
Sphere.center = [-1, 0, -1]
Sphere.radius = 0.5
Sphere.material.Dielectric.refractive_index = 1.5

# Right
[[world]]
Sphere.center = [1, 0, -1]
Sphere.radius = 0.5
Sphere.material.Metal.albedo = [0.8, 0.6, 0.2]
Sphere.material.Metal.fuzz = 0.0

[image]
width = 426
height = 240
samples_per_pixel = 100
max_ray_depth = 50

[camera]
look_from = [3, 3, 2]
look_to = [0, 0, -1]
vertical_fov = 20
aperture = 2
