
# Ground
[[world]]
Sphere.center = [0, -100.5, -1]
Sphere.radius = 100
Sphere.material.Lambertian.albedo = [0.8, 0.8, 0.0]

# Center
[[world]]
Sphere.center = [0, 0, -1.0]
Sphere.radius = 0.5
Sphere.material.Lambertian.albedo = [0.7, 0.3, 0.3]

# Left
[[world]]
Sphere.center = [-1, 0, -1]
Sphere.radius = 0.5
Sphere.material.Metal.albedo = [0.8, 0.8, 0.8]
Sphere.material.Metal.fuzz = 0.3

# Right
[[world]]
Sphere.center = [1, 0, -1]
Sphere.radius = 0.5
Sphere.material.Metal.albedo = [0.8, 0.6, 0.2]
Sphere.material.Metal.fuzz = 1.0

[image]
width = 426
height = 240
samples_per_pixel = 100
max_ray_depth = 50
